### ISSUE TITLE
Does not work with Hyper 2.0.0-canary.9

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/hyper-background#2]
It does not change the background of the terminal and only the parts surrounding it.

**Comment by radi-cho** [comment]
2.0.0 is here. Did you resolve this issue?

**Comment by retrixe** [comment]
It isn't here. Also, I have found the solution but it didn't seem to work on canary 16.

**Comment by radi-cho** [comment]
"It isn't here" - @retrixe? Then why I was prompted to update and linked to this: https://github.com/zeit/hyper/releases/tag/2.0.0?

**Comment by retrixe** [comment]
"here" refers to the patch, kindly acknowledge.

Funnily and coincidentally, I am also on the canary branch, and Hyper told me to update to 2.0.0-canary.18 which is the same as release 2.

**Comment by retrixe** [comment]
@kamen94 an experimental patch is available in the latest commit to master, however I do not recommend it, as the terminal header becomes... very ugly and unusable. I will be refining and fixing the patch soon, available by tomorrow.
