### ISSUE TITLE
Support for Hyper v3

### ISSUE THREAD

**Issue by bormanjo** [RSG-Group/hyper-background#21]
Trying to use this plugin on the latest Hyper and my whole background goes blank/white (no image is rendered).

**Comment by bormanjo** [comment]
Disregard - Figured it out :smile:

**Comment by abruyat** [comment]
@bormanjo I have the same issue, What did you do to solve it?

**Comment by abruyat** [comment]
This happened if the image selected is not present, giving a correct image path solve this
