### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by BitStandByYou** [RSG-Group/hyper-background#4]

**Comment by radi-cho** [comment]
Hello @kamen94. Can you provide more detailed information about your problem - such as hyper version, installation method that you used, error displayed, how to reproduce or why you think it is not working? It may be related to #2, It may be related to something else or the problem may be on your side.

**Comment by BitStandByYou** [comment]
@radi-cho Sorry, I'm using hyper 2.0.0 (the latest stable release) on Windows, The path I set in the settings file was `D:\\sun_s\\Pictures\\terminal.jpg`, When I started the hyper program,The backbround picture was not shown, It Just like I didn't install hyper-background. And the hyper doesn't throw any errors. Should I provide you with index.html?

**Comment by radi-cho** [comment]
Thanks, @kamen94. I think it's related to #2 ("Does not work with Hyper 2.0.0-canary.9"). cc @retrixe

**Comment by retrixe** [comment]
Duplicate issue of #2 and currently being fixed.

**Comment by retrixe** [comment]
Duplicate issue of #2 and currently being fixed.

Like literally, I'm fixing it right now.

**Comment by retrixe** [comment]
Locking off conversation here, continued discussion in #2.
