### ISSUE TITLE
Attempting to install hyper-background

### ISSUE THREAD

**Issue by SunbeamRapier** [RSG-Group/hyper-background#7]
Mac OS Catalina

a) What directory should I be in to run the npm i hyper-background command?  I installed it in the root directory but got an error: "No package.json found: Cannot audit a project without a package.json"

So i installed in a reactjJS project file but cannot find a .hyper.js file anywhere on this Mac even allowing hidden files to be displayed.  Where should it be?

b) there is no reference to hyper-background in any file on this Mac except in the hyper file in node_modules

Any suggestions?

**Comment by retrixe** [comment]
This isn't a regular npm module, it's an extension for [Hyper](https://hyper.is), a terminal app. It's of no use when installing it in a React project or such with `npm`, this extension is only published on `npm` because Hyper pulls extensions from `npm`.
